function creaFigura() {
    var mioCanvas = document.getElementById("canvas1");
    var ctx = mioCanvas.getContext("2d");
    ctx.beginPath();
    ctx.arc(200, 200, 150, 0, Math.PI*2, true);
    ctx.lineWidth = 15;
    ctx.strokeStyle = "Yellow";
    ctx.fillStyle = "Yellow";
    ctx.fill();
    ctx.stroke();
    ctx.closePath();
    ctx.beginPath();
    ctx.arc(140, 140, 40, 0, Math.PI*2, true);
    ctx.lineWidth = 15;
    ctx.strokeStyle = "black";
    ctx.fillStyle = "black";
    ctx.fill();
    ctx.stroke();
    ctx.closePath();
    ctx.beginPath();
    ctx.arc(260, 140, 40, 0, Math.PI*2, true);
    ctx.lineWidth = 15;
    ctx.strokeStyle = "black";
    ctx.fillStyle = "black";
    ctx.fill();
    ctx.stroke();
    ctx.closePath();
    ctx.beginPath();
    ctx.arc(140, 140, 10, 0, Math.PI*2, true);
    ctx.lineWidth = 15;
    ctx.strokeStyle = "white";
    ctx.fillStyle = "white";
    ctx.fill();
    ctx.stroke();
    ctx.closePath();
    ctx.beginPath();
    ctx.arc(260, 140, 10, 0, Math.PI*2, true);
    ctx.lineWidth = 15;
    ctx.strokeStyle = "white";
    ctx.fillStyle = "white";
    ctx.fill();
    ctx.stroke();
    ctx.closePath();
    ctx.beginPath();
    ctx.arc(200, 250, 60, Math.PI, 0, true);
    ctx.lineWidth = 15;
    ctx.strokeStyle = "red";
    ctx.fillStyle = "red";
    ctx.fill();
    ctx.stroke();
    ctx.closePath();
}